test_that("range finding works ", {
  expect_true(in_range(1, range(1, 2)))
  expect_error(in_range(1, 2))
  expect_error(in_range(1, c(2,1)))
  expect_false(in_range_strict(1, range(1, 2)))
  expect_error(in_range_strict(1, 2))
  expect_error(in_range_strict(1, c(2,1)))
  expect_equal(first_up("in"), "In")
  expect_equal(first_up("iN"), "IN")
  expect_equal(find_pretty_ylim(c(1, 3, 10)), c(0, 12))
  expect_equal(0, nrow(apply_xlims(data.frame(period = as.Date("2010/01/01")))))
  expect_equal(1, nrow(apply_xlims(data.frame(period = as.Date("2011/02/01")))))
})
